### ISSUE TITLE
Download Data button does not function

### ISSUE THREAD

**Issue by sietecielos** [Servir-Mekong/LandCoverMonitoring#3]
After selecting area of interest and clicking "Download Data" button, no action occurs and data is not downloaded. (Tested in Chrome on Windows 10 64 Bit).

**Comment by biplovbhandari** [comment]
Hi, @sietecielos thanks for using the issue page here. I think there is some step missed. Once you select an area of interest. Then the right side of 'Download Data/Typology' button, there is a drop-down which lists the type of download. Please try it again using the way I mentioned and let know.
![image](https://user-images.githubusercontent.com/4207677/41514223-35e2307a-72e0-11e8-804d-b89fa2c33138.png)

**Comment by sietecielos** [comment]
@biplovbhandari, thank you for the reply. I do not see another step to follow and have tested this in Chrome and Firefox. It appears there may be two issues: (1) If a larger area of interest is selected the system does not produce the download link (is there a maximum area of interest size?). (2) If a smaller area is selected the download button appears, but there is no dropdown menu, just a direct download of a  zipped folder when the download button is clicked. I did not want to open these as distinct issues before checking again, but this is what I see on my system.
![image](https://user-images.githubusercontent.com/8274112/41516063-7439eaf8-7267-11e8-9ffb-54f8b529f0b7.png)
